# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwitchMedia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwitchMedia
	pod 'ObjectMapper', '~> 2.2'
  	pod "PromiseKit", "~> 4.0”
	pod 'SDWebImage', '~>3.8'

  target 'SwitchMediaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwitchMediaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
